# Generated by Django 5.0.3 on 2024-03-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('question_answer_rate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lectures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('lecture_satisfaction', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('textbook', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('lecture_id', models.CharField(max_length=100)),
                ('started_at', models.CharField(max_length=100)),
                ('ended_at', models.CharField(max_length=100)),
                ('score', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
            ],
        ),
    ]
